apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-myinfra-kafkaui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-myinfra-kafkaui
  template:
    metadata:
      labels:
        app: app-myinfra-kafkaui
    spec:
      containers:
      - name: container-myinfra-kafkaui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_CLUSTERS_0_NAME
          value: "local-cluster"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "svc-myinfra-kafka.svc.cluster.local:9092"   # your kafka service name + port
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "svc-myinfra-zookeeper:2181"  # optional, needed if UI needs ZK
