apiVersion: v1
kind: Service
metadata:
  name: svc-myinfra-kafkaui
spec:
  type: NodePort   # or ClusterIP if you want to use port-forward
  selector:
    app: app-myinfra-kafkaui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # only for NodePort access
