apiVersion: v1
kind: Service
metadata:
  name: mykafkaui
  namespace: mykafkaui
spec:
  type: NodePort   # or ClusterIP if you want to use port-forward
  selector:
    app: mykafkaui
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080  # only for NodePort access
